version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:4989
    volumes:
      - .:/code
    ports:
      - "4989:4989"