# Generated by Django 4.1 on 2023-03-23 13:24
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'myapp/fixture/prefecture.json', app_label='myapp')

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_target_consideration_restaurant'),
    ]

    operations = [
      migrations.RunPython(load_fixture),
    ]
